### PR TITLE
ci: Add Winget Releaser workflow

### PR DESCRIPTION
**Pull request by sitiom**
[This action](https://github.com/vedantmgoyal2009/winget-releaser) automatically generates manifests for Winget Community Repository ([microsoft/winget-pkgs](https://github.com/microsoft/winget-pkgs)) and submits them.

gdu is available in Winget ([winget package](https://repology.org/project/gdu/versions)) but is outdated. I have manually created a PR to update it for now (https://github.com/microsoft/winget-pkgs/pull/96456), but this workflow should automatically keep it up to date for the new versions.

**Before merging this:**
1. Add a **classic** PAT with `public_repo` scope as a repository secret named `WINGET_TOKEN`.

example

2. Fork https://github.com/microsoft/winget-pkgs under @dundee. The action will use that fork for making a branch and creating a PR with the upstream [winget-pkgs](https://github.com/microsoft/winget-pkgs) repository on every release.
3. Install [Pull](https://github.com/apps/pull) on the winget-pkgs fork to ensure that it is constantly updated.

You can test out the action inputs in this [playground](https://bittu.eu.org/docs/wr-playground).

If you want to see an example of a PR created using this action, see [microsoft/winget-pkgs/pulls (Pull request has been automatically created using 🛫 WinGet Releaser)](https://github.com/microsoft/winget-pkgs/pulls?q=is%3Apr+sort%3Aupdated-desc+Pull+request+has+been+automatically+created+using+%F0%9F%9B%AB+WinGet+Releaser).

### CODE REVIEW

**Review by dundee — APPROVED** [review]

**Comment by dundee** [comment]
Thanks for your PR!

**Comment by sitiom** [comment]
@dundee https://github.com/dundee/gdu/actions/runs/4647275371/jobs/8224182171
Winget Releaser workflow failed. Did you forget to put the `WINGET_TOKEN` secret in this repo?
image

**Comment by sitiom** [comment]
@dundee

**Comment by sitiom** [comment]
@dundee

**Comment by sitiom** [comment]
@dundee https://github.com/dundee/gdu/actions/runs/4647275371/jobs/8224182171
Winget Releaser workflow failed. Did you forget to put the `WINGET_TOKEN` secret in this repo?
image

I have manually created a PR for now: https://github.com/microsoft/winget-pkgs/pull/102030.

**Comment by dundee** [comment]
I have somehow miseed the step. Fixed. Thanks!

**Comment by dundee** [comment]
https://github.com/dundee/gdu/actions/runs/4647275371/jobs/8292671195

**Pull request merged**
