### PR TITLE
Make the bar graph meaningful in large directories

### PR DESCRIPTION
**Pull request by chutzimir**
The current bar implementation shows an empty graph in a directory with
approximately 20 files (not so uncommon) of similar size - each file
size is 5% of the total, which rounds to 0 for the bar of 10 ticks.
With directories with more items, the usefulness of the bar degrades
even faster even for objects of different sizes.

With this change, all sizes are shown relative to the largest
item which gives a better idea of how big the items are.

### CODE REVIEW

**Comment by dundee** [comment]
Hi @chutzimir, thanks for the PR!

We have already discussed this topic in #82. I think both approaches have its meaning and we should probably offer the user the possibility to switch between them. 

We may use shortcut `B` (big b) for this. 

Are you willing to add the switching to the PR?

**Comment by OliverLew** [comment]
A CLI argument in addition would be even better :)

**Comment by dundee** [comment]
> A CLI argument in addition would be even better :)

We can add both.

**Comment by dundee** [comment]
@chutzimir Looks very nice!

Last thing: could you fix the failing tests?

**Pull request merged**
