### PR TITLE
feat: crop current item path to 70 chars

### PR DESCRIPTION
**Pull request by dundee**
#172

### CODE REVIEW

**Comment by dundee** [comment]
Snímek obrazovky z 2022-09-14 00-16-58

@edrozenberg @daniejstriata What do you think?

From my point of view is more important to see the beginning of the path, so you know where approximately is the analysis running. Therefore I cut off the end of path if it's too long.

**Comment by edrozenberg** [comment]
@dundee it's a bit tricky, seeing the beginning gives you the context, but seeing the end is also important to be able to see that activity is going on (filename keeps changing). One possibility is something like:

/beginning/something/something/......./last path element/filename

So priority would be to show the last path element and filename, then show as much of the beginning as fits.

For ex:

`/Volume/myfiles/joe/documents/.../2022/important.docx`

**Comment by dundee** [comment]
Sounds good, I will try to implement it.

**Comment by daniejstriata** [comment]
@dundee :-) Now that you're updating that modal... Won't it be interesting to see the running time too?

**Comment by dundee** [comment]
path shortening

**Comment by dundee** [comment]
With time:
progress with time

**Comment by edrozenberg** [comment]
That looks great. For the future might be nice to have a config option to allow showing multiple lines for current item for users who want to see more of the path, but it's fine as is with the latest changes.

Also would be perfect if modal could be vertically centered, currently it displays at a fixed position of X lines (10?) below the top - on small terminals it displays too low, on taller terminals too high. Thank you.

**Comment by dundee** [comment]
Happy to hear that! 

Yes, I have fixed the vertical alignment as well.

**Comment by edrozenberg** [comment]
The totals line is getting wiped out most of the time currently.

I ran `gdu --write-config` to gen a template config, then modified style in `.gdu.yaml`:

```
style:
    selected-row:
        text-color: ""
        background-color: ""
    progress-modal:
        current-item-path-max-len: 800
```

The modal still shows only 1 or 2 lines and wipes out the Totals line a lot of the time:
Modal Missing Totals

**Comment by dundee** [comment]
Not sure how to solve this properly. Only thing that comes to my mind is to make the height of the modal configurable.

**Comment by edrozenberg** [comment]
I don't know but it `current-item-path-max-len` would work, I could set it to 20 lines and never have Totals disappear. Thanks.

**Comment by dundee** [comment]
`current-item-path-max-len` sets the maximal number of characters, not lines. If you leave it as it is (70 chars), you should be good.

**Comment by edrozenberg** [comment]
I didn't understand how that max is intended to work, now I do. There is no more any option to see multiple path lines, single line only, so you spec the number of chars that can fit in the width of the terminal window you normally use - for me 50 works.

Since it displays very little info now, the path line is essentially an activity indicator, and along with the totals line, you can see that scanning is happening. Good enough for now, and the totals line is always visible. Thanks.

**Pull request merged**
